# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('text', models.CharField(max_length=250)),
                ('photo', models.FileField(null=True, upload_to='')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gammaukr.Models')),
            ],
        ),
        migrations.CreateModel(
            name='Projects_steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_num', models.IntegerField()),
                ('text', models.CharField(max_length=600, null=True)),
                ('photo', models.FileField(null=True, upload_to='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gammaukr.Projects')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('photo', models.FileField(upload_to='')),
                ('text', models.CharField(max_length=1000, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gammaukr.Services'),
        ),
    ]
