# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gammaukr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects_steps',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
