# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gammaukr', '0002_auto_20170706_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gammaukr.Models'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gammaukr.Services'),
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
