# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gammaukr', '0004_auto_20170706_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('text', models.TextField(blank=True, null=True)),
                ('photo', models.FileField(null=True, upload_to='')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gammaukr.Models')),
            ],
        ),
        migrations.CreateModel(
            name='News_steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_num', models.IntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gammaukr.News')),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projects_steps',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gammaukr.Services'),
        ),
    ]
