# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmsite', '0003_servicessecond_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.FileField(blank=True, null=True, upload_to='')),
                ('photo2', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='HomePhoto',
        ),
        migrations.RemoveField(
            model_name='image',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='service',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='start',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='text',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='top',
        ),
        migrations.AddField(
            model_name='gallery',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmsite.Models'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmsite.Services'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='textblock',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmsite.Projects'),
        ),
        migrations.AddField(
            model_name='imageblock',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmsite.Projects'),
        ),
    ]
