# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmsite', '0004_auto_20171130_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='start',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
