# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmsite', '0005_auto_20171130_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textblock',
            name='project',
        ),
        migrations.AddField(
            model_name='imageblock',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TextBlock',
        ),
    ]
