# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmsite', '0006_auto_20171130_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBlockNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('photo1', models.FileField(blank=True, null=True, upload_to='')),
                ('photo2', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesSecondContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('photo', models.FileField(upload_to='')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmsite.ServicesSecond')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesSecondPriceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmsite.ServicesSecond')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesSecondPriceTableElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pricefrom', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('priceto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmsite.ServicesSecondPriceTable')),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='service',
        ),
        migrations.RemoveField(
            model_name='news',
            name='text',
        ),
        migrations.AddField(
            model_name='imageblocknews',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmsite.News'),
        ),
    ]
