# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmsite', '0007_auto_20171201_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicessecondcontent',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
