# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmsite', '0008_auto_20171201_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicessecondpricetableelement',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmsite.Gallery'),
        ),
        migrations.AddField(
            model_name='servicessecondpricetableelement',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmsite.News'),
        ),
        migrations.AddField(
            model_name='servicessecondpricetableelement',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmsite.Projects'),
        ),
        migrations.AlterField(
            model_name='servicessecondpricetableelement',
            name='notes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='servicessecondpricetableelement',
            name='pricefrom',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicessecondpricetableelement',
            name='priceto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
