# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmsite', '0010_auto_20171202_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='top',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmsite.ServicesSecond'),
        ),
    ]
