# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmsite', '0012_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='shortname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
