# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmsite', '0013_auto_20171205_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedVacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('money', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='needvacancy',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmsite.Vacancy'),
        ),
    ]
