# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 00:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmsite', '0017_auto_20171207_0128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='models',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='show',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='news',
            name='start',
        ),
        migrations.AddField(
            model_name='gallery',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 2, 8, 19, 405740)),
        ),
        migrations.AddField(
            model_name='news',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 2, 8, 19, 404740)),
        ),
        migrations.AddField(
            model_name='projects',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 2, 8, 19, 403740)),
        ),
    ]
