# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 01:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmsite', '0018_auto_20171207_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': '-Ссылки на сайты',
            },
        ),
        migrations.CreateModel(
            name='MainText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=200)),
                ('second', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Номер телефона', 'verbose_name_plural': '-Номера телефонов'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': '-Галереи'},
        ),
        migrations.AlterModelOptions(
            name='models',
            options={'verbose_name': 'Модель', 'verbose_name_plural': '-Модели'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': '-Новости'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Проект', 'verbose_name_plural': '-Проекты'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': '-Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': '-Услуги'},
        ),
        migrations.AlterModelOptions(
            name='servicessecond',
            options={'verbose_name': 'Подуслуга', 'verbose_name_plural': '-Подуслуги'},
        ),
        migrations.AlterModelOptions(
            name='servicessecondpricetable',
            options={'verbose_name': 'Таблица цен', 'verbose_name_plural': '-Таблицы цен подуслуг'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': '-Вакансии'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 3, 24, 47, 18137)),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 3, 24, 47, 17137)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 3, 24, 47, 15136)),
        ),
    ]
