# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 02:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmsite', '0019_auto_20171207_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 4, 8, 47, 392157)),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 4, 8, 47, 391157)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 4, 8, 47, 389157)),
        ),
    ]
