# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 00:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmsite', '0021_auto_20171207_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionsGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.TextField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Мета-теги Галерей',
                'verbose_name_plural': '-Мета-теги Галерей',
            },
        ),
        migrations.CreateModel(
            name='DescriptionsNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.TextField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Мета-теги Новостей',
                'verbose_name_plural': '-Мета-теги Новостей',
            },
        ),
        migrations.CreateModel(
            name='DescriptionsProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.TextField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Мета-теги Проектов',
                'verbose_name_plural': '-Мета-теги Проектов',
            },
        ),
        migrations.CreateModel(
            name='DescriptionsServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.TextField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Мета-теги Услуг',
                'verbose_name_plural': '-Мета-теги Услуг',
            },
        ),
        migrations.AddField(
            model_name='maintext',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='maintext',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 8, 2, 51, 57, 146654)),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 8, 2, 51, 57, 145654)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 8, 2, 51, 57, 143654)),
        ),
    ]
